name: Minimal Deployment Pipeline

on:
  push:
    branches:
      - main
      - qa
    paths:
      - 'manifests/**.yaml'
      - 'tenant-specific-overrides/**/*.yaml'
      - .github/workflows/*.yml
      - 'deploy'
      - 'generate-tenant-jobs'

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug workspace
        run: |
          pwd
          ls -la
          
      - name: Make scripts executable
        run: |
          chmod +x generate-tenant-jobs
          chmod +x deploy

      - name: Generate Tenant Jobs
        run: ./generate-tenant-jobs

      - name: Show Generated Pipeline
        run: cat tenant-deployment-pipeline.yml

      - name: Deploy
        run: ./deploy
      
      - name: Show generated files
        run: |
          ls -R deployment-configs
          cat deployment-configs/*.txt
          echo "---- JSON File ----"
          cat deployment-configs/*.json
