name: Minimal Deployment Pipeline

on:
  push:
    branches:
      - main
      - qa
    paths:
      - 'manifests/**.yaml'
      - 'tenant-specific-overrides/**/*.yaml'

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug workspace
        run: |
          pwd
          ls -la
          
      - name: Make scripts executable
        run: |
          chmod +x generate-tenant-jobs
          chmod +x deploy

      - name: Generate and Deploy
        run: |
          ./generate-tenant-jobs
          ./deploy